--equi join
    --SELECT의 속성 값 -1개의 WHERE을 주어야 한다.
--업무코드가 FI_MGR인 사원의 사원번호, 이름, 급여, 부서코드, 근무지코드 조회
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID, D.LOCATION_ID FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.JOB_ID = 'FI_MGR' AND E.DEPARTMENT_ID = D.DEPARTMENT_ID ORDER BY FIRST_NAME;

--사원명, 부서명, 급여, 근무도시명 조회
SELECT E.FIRST_NAME, D.DEPARTMENT_NAME, E.SALARY, L.CITY FROM EMPLOYEES E, LOCATIONS L , DEPARTMENTS D
WHERE  E.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID;

