--Seattle에 근무하는 사원 중 급여 5000이상인 사원의 사원명, 급여, 업무명, 입사일, 보너스비율, 부서코드, 도서명을 사원명 순으로 정렬하여 조회
SELECT E.FIRST_NAME AS NAME, E.SALARY AS SAYARY ,J.JOB_TITLE AS JOB, E.HIRE_DATE AS HIREDATE, E.COMMISSION_PCT AS BONUS,
E.DEPARTMENT_ID AS DEPT, L.CITY AS CITY
FROM EMPLOYEES E, LOCATIONS L , DEPARTMENTS D, JOBS J -- TABLE 4개
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID AND J.JOB_ID = E.JOB_ID -- JOIN조건 3개(TABLE - 1)
AND L.CITY = 'Seattle' AND E.SALARY >= 5000
ORDER BY 1;

--MANAGER JOB을 가진 사람들의 부서명, 이름, 업무명 조회
SELECT D.DEPARTMENT_NAME, E.FIRST_NAME,J.JOB_TITLE
FROM EMPLOYEES E, DEPARTMENTS D, JOBS J
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID  AND J.JOB_ID = E.JOB_ID
AND J.JOB_TITLE LIKE '%Manager'
ORDER BY E.FIRST_NAME;

--Micheal의 이름과 해당 부서가 위치한 도시 및(행정구역 상의) 지역 조회
SELECT E.FIRST_NAME, L.CITY, L.STATE_PROVINCE
FROM EMPLOYEES E, LOCATIONS L, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID  AND L.LOCATION_ID = D.LOCATION_ID
AND E.FIRST_NAME = 'Michael'
ORDER BY L.CITY;
