--Seattle에 근무하는 사원 중 급여 5000이상인 사원의 사원명, 급여, 업무명, 입사일, 보너스비율, 부서코드, 도서명을 사원명 순으로 정렬하여 조회
SELECT E.FIRST_NAME AS NAME, E.SALARY AS SAYARY ,J.JOB_TITLE AS JOB, E.HIRE_DATE AS HIREDATE, E.COMMISSION_PCT AS BONUS,
E.DEPARTMENT_ID AS DEPT, L.CITY AS CITY
FROM EMPLOYEES E, LOCATIONS L , DEPARTMENTS D, JOBS J -- TABLE 4개
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND D.LOCATION_ID = L.LOCATION_ID AND J.JOB_ID = E.JOB_ID -- JOIN조건 3개(TABLE - 1)
AND L.CITY = 'Seattle' AND E.SALARY >= 5000
ORDER BY 1;

--MANAGER JOB을 가진 사람들의 부서명, 이름, 업무명 조회
SELECT D.DEPARTMENT_NAME, E.FIRST_NAME,J.JOB_TITLE
FROM EMPLOYEES E, DEPARTMENTS D, JOBS J
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID  AND J.JOB_ID = E.JOB_ID
AND J.JOB_TITLE LIKE '%Manager'
ORDER BY E.FIRST_NAME;

--Micheal의 이름과 해당 부서가 위치한 도시 및(행정구역 상의) 지역 조회
SELECT E.FIRST_NAME, L.CITY, L.STATE_PROVINCE
FROM EMPLOYEES E, LOCATIONS L, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID  AND L.LOCATION_ID = D.LOCATION_ID
AND E.FIRST_NAME = 'Michael'
ORDER BY L.CITY;

--부서명과 부서별 업무코드 및 각 부서별 CLERK 업무코드(_CLERK)를 가진 사람의 수 조회(부서명 순으로 정렬)
SELECT D.DEPARTMENT_NAME, E.JOB_ID, COUNT(*)
FROM DEPARTMENTS D, EMPLOYEES E
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.JOB_ID LIKE '%_CLERK'
GROUP BY D.DEPARTMENT_NAME, E.JOB_ID
ORDER BY D.DEPARTMENT_NAME;

--각 부서별 평균 급여 조회(부서명 순으로 정렬)
SELECT D.DEPARTMENT_NAME, TRUNC(AVG(E.SALARY))
FROM DEPARTMENTS D, EMPLOYEES E
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
ORDER BY D.DEPARTMENT_NAME;

-- NON-EQUI JOIN
SELECT FIRST_NAME, JOB_ID, SALARY FROM EMPLOYEES ORDER BY JOB_ID;
SELECT * FROM JOBS ORDER BY JOB_ID;

--급여가 최소급여와 최대급여 사이인 사원의 사원번호, 사원 명, 업무코드, 급여, 업무명, 업무의 최소급여, 업무의 최대 급여를 업무코드 순으로 조회 
SELECT E.DEPARTMENT_ID, E.FIRST_NAME, E.JOB_ID, E.SALARY, J.JOB_TITLE, J.MIN_SALARY, J.MAX_SALARY
FROM JOBS J, EMPLOYEES E
WHERE E.JOB_ID = J.JOB_ID AND E.SALARY >= J.MIN_SALARY AND E.SALARY <= J.MAX_SALARY  --EQUI JOIN도 필요하다.
ORDER BY J.JOB_ID; 

--OUTER JOIN
--(+)기호를 안 써준 쪽이 기준이 된다.
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.JOB_ID,  E.DEPARTMENT_ID, D.DEPARTMENT_ID,  D.DEPARTMENT_NAME
FROM DEPARTMENTS D, EMPLOYEES E
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID(+);--사장 까지 111개 나옴

SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.JOB_ID,  E.DEPARTMENT_ID, D.DEPARTMENT_ID,  D.DEPARTMENT_NAME
FROM DEPARTMENTS D, EMPLOYEES E
WHERE E.DEPARTMENT_ID(+) = D.DEPARTMENT_ID;--사용하지 않는 부서까지 126개 나옴
--(+)기호는 양 쪽 다 사용할 수 없다.




