--JOIN ~ ON
--사원명, 급여, 해당 사원의 매니저명, 매니저급여 조회(JOIN ~ ON 구문 이용)
SELECT E1.FIRST_NAME, E1.SALARY, E2.FIRST_NAME, E2.SALARY
FROM EMPLOYEES E1 JOIN EMPLOYEES E2 ON E1.MANAGER_ID = E2.EMPLOYEE_ID;

--이름에 A,a 문자가 없는 사원의 사원명, 부서명, 근무도시 정보 조회(사원명 순으로 정렬)
SELECT E.FIRST_NAME, D.DEPARTMENT_NAME, L.CITY 
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE E.FIRST_NAME NOT LIKE '%a%' AND E.FIRST_NAME NOT LIKE '%A%'
ORDER BY 1;

--OUTER JOIN
SELECT * FROM EMPLOYEES E FULL OUTER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;
SELECT * FROM EMPLOYEES E LEFT OUTER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;--EMPLOYEES가 기준
SELECT * FROM EMPLOYEES E RIGHT OUTER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;--DEPARTMENT가 기준

