--급여를 2000보다 많이 받는 사원들의 이름, 급여, 부서번호, 부서명 조회(모든 부서테이블 조인)
SELECT E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E RIGHT OUTER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID AND SALARY(+) > 2000; --(+)상관없음

--급여를 2000보다 많이 받는 사원들의 이름, 급여, 부서번호, 부서명 조회(모든 회원테이블 조인)
SELECT E.FIRST_NAME, E.SALARY, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E LEFT OUTER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID AND SALARY > 2000;

--서브쿼리
--SINGLE ROW SUBQUERY
SELECT FIRST_NAME, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID = (SELECT JOB_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 120);

--150번 사원보다 급여가 많은 사원의 이름과 급여를 급여가 많은 순으로 조회
SELECT FIRST_NAME, SALARY 
FROM EMPLOYEES
WHERE SALARY > (SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 150)
ORDER BY SALARY DESC;

--급여를 가장 많이 받는 사원의 이름, 부서번호, 급여, 입시일 조회
SELECT FIRST_NAME, DEPARTMENT_ID, SALARY, HIRE_DATE
FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

--급여가 평균 급여보다 적은 사원의 사원번호, 이름, 업무코드, 급여, 부서번호 조회
SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES);

--사원번호가 162인 사원과 업무가 같고, 급여가 Clara보다 많은 사원의 사원번호, 이름, 담당업무명, 입사일자, 급여 조회
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, J.JOB_TITLE, E.HIRE_DATE, E.SALARY
FROM EMPLOYEES E, JOBS J 
WHERE E.JOB_ID = J.JOB_ID 
AND E.JOB_ID = (SELECT JOB_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 162) 
AND E.SALARY > (SELECT SALARY FROM EMPLOYEES WHERE FIRST_NAME = 'Clara');

--부서별 최소급여가 80번 부서의 최소급여보다 많은 부서의 부서번호와 최소급여 조회
SELECT DEPARTMENT_ID, MIN(SALARY)
FROM EMPLOYEES 
GROUP BY department_id
HAVING MIN(SALARY) > (SELECT MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = 80);
















