SELECT DEPARTMENT_ID, MAX(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID;

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE SALARY IN (SELECT MAX(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID)
ORDER BY DEPARTMENT_ID;

--업무가 sales인 최소 한 명 이상의 사원보다 급여를 많이 받는 사원의 이름, 급여, 업무코드를 급여 순으로 조회
SELECT FIRST_NAME, SALARY, JOB_ID
FROM EMPLOYEES
WHERE SALARY >ANY (SELECT SALARY FROM EMPLOYEES JOIN JOBS USING (JOB_ID) WHERE JOB_TITLE LIKE '%sales%' OR JOB_TITLE LIKE 'Sales%')
ORDER BY SALARY;

SELECT MIN(SALARY) FROM EMPLOYEES WHERE JOB_ID IN ('SA_MAN', 'SA_REP');



