-- USER SQL
CREATE USER "HONG" IDENTIFIED BY "1234"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "HONG" QUOTA 10M ON "USERS";

-- ROLES
GRANT "CONNECT" TO "HONG" ;
GRANT "RESOURCE" TO "HONG" ;

-- SYSTEM PRIVILEGES

