DROP TABLE KEYTBA;
DROP TABLE KEYTAB2;
DROP TABLE TESTTAB;
DROP SEQUENCE SEQUENCE1;

CREATE TABLE TESTTAB 
(
  COLUMN1 VARCHAR2(20 BYTE) NOT NULL 
, COLUMN2 VARCHAR2(20 BYTE) NOT NULL 
, COLUMN3 VARCHAR2(20 BYTE) 
, COLUMN4 VARCHAR2(20 BYTE) 
, CONSTRAINT TESTTAB_PK PRIMARY KEY 
  (
    COLUMN1 
  )
  ENABLE
);

CREATE TABLE KEYTBA 
(
  COLUMN1 VARCHAR2(20 BYTE) 
, COLUMN2 VARCHAR2(20 BYTE) 
, COLUMN3 VARCHAR2(20 BYTE) NOT NULL 
, COLUMN4 VARCHAR2(20 BYTE) 
, CONSTRAINT KEYTBA_PK PRIMARY KEY 
  (
    COLUMN1 
  )
  ENABLE
);

CREATE TABLE KEYTAB2 
(
  COLUMN1 VARCHAR2(20) NOT NULL 
, COLUMN2 VARCHAR2(20) 
, COLUMN3 VARCHAR2(20) 
, CONSTRAINT KEYTAB2_PK PRIMARY KEY 
  (
    COLUMN1 
  )
  ENABLE 
);


ALTER TABLE KEYTBA
ADD CONSTRAINT KEYTBA_FK1 FOREIGN KEY
(
  COLUMN1 
)
REFERENCES TESTTAB
(
  COLUMN1 
)
ENABLE;

CREATE SEQUENCE SEQUENCE1 INCREMENT BY 1 START WITH 1;

CREATE TRIGGER KEYTAB2_TRG 
BEFORE INSERT ON KEYTAB2 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.COLUMN1 IS NULL THEN
      SELECT SEQUENCE1.NEXTVAL INTO :NEW.COLUMN1 FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

INSERT INTO "HONG"."TESTTAB" (COLUMN1, COLUMN2, COLUMN3, COLUMN4) VALUES ('A', 'A', 'A', 'A');
INSERT INTO "HONG"."TESTTAB" (COLUMN1, COLUMN2, COLUMN3, COLUMN4) VALUES ('B', 'B', 'B', 'B');
INSERT INTO "HONG"."TESTTAB" (COLUMN1, COLUMN2, COLUMN3, COLUMN4) VALUES ('C', 'C', 'C', 'C');
INSERT INTO "HONG"."TESTTAB" (COLUMN1, COLUMN2, COLUMN3, COLUMN4) VALUES ('D', 'D', 'D', 'D');


INSERT INTO "HONG"."KEYTBA" (COLUMN1, COLUMN2, COLUMN3, COLUMN4) VALUES ('A', 'A', 'A', 'A');
INSERT INTO "HONG"."KEYTBA" (COLUMN1, COLUMN2, COLUMN3, COLUMN4) VALUES ('B', 'B', 'B', 'B');
INSERT INTO "HONG"."KEYTBA" (COLUMN1, COLUMN2, COLUMN3, COLUMN4) VALUES ('C', 'C', 'C', 'C');
INSERT INTO "HONG"."KEYTBA" (COLUMN1, COLUMN2, COLUMN3, COLUMN4) VALUES ('D', 'D', 'D', 'D');

INSERT INTO "HONG"."KEYTAB2" (COLUMN1, COLUMN2, COLUMN3) VALUES ('A', 'A', 'A');
INSERT INTO "HONG"."KEYTAB2" (COLUMN1, COLUMN2, COLUMN3) VALUES ('S', 'S', 'S');
INSERT INTO "HONG"."KEYTAB2" (COLUMN1, COLUMN2, COLUMN3) VALUES ('D', 'D', 'D');



