DROP TABLE TABLE1;

CREATE TABLE TABLE1 
(
  COLUMN1 VARCHAR2(20) NOT NULL 
, COLUMN2 VARCHAR2(20) 
, COLUMN3 VARCHAR2(20) 
, COLUMN4 VARCHAR2(20) 
);
INSERT INTO "HONG"."TABLE1" (COLUMN1, COLUMN2, COLUMN3, COLUMN4) VALUES ('A', 'A', 'A', 'A');
INSERT INTO "HONG"."TABLE1" (COLUMN1, COLUMN2, COLUMN3, COLUMN4) VALUES ('B', 'B', 'B', 'B');
INSERT INTO "HONG"."TABLE1" (COLUMN1, COLUMN2, COLUMN3, COLUMN4) VALUES ('C', 'C', 'C', 'C');
INSERT INTO "HONG"."TABLE1" (COLUMN1, COLUMN2, COLUMN3, COLUMN4) VALUES ('D', 'D', 'D', 'D');

