--TABLE에 ALIAS 사용하는 방법(AS 사용 X)
SELECT FIRST_NAME, EMP.DEPARTMENT_ID, DEP.DEPARTMENT_ID, DEPARTMENT_NAME
FROM EMPLOYEES EMP, DEPARTMENTS DEP;

--EQUL JOIN(WHERE 없으면 카디시안 곱 발생)
SELECT FIRST_NAME, EMPLOYEES.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_ID, DEPARTMENT_NAME
FROM EMPLOYEES, DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

