DROP TABLE MEMBERTBL;
DROP TABLE PRODUCTTBL;

CREATE TABLE MEMBERTBL 
(
  MEMBERID CHAR(8) NOT NULL 
, MEMBERNAME NCHAR(5) NOT NULL 
, MEMBERADDRESS NVARCHAR2(20) 
, CONSTRAINT MEMBERTBL_PK PRIMARY KEY 
  (
    MEMBERID 
  )
  ENABLE 
);
CREATE TABLE PRODUCTTBL 
(
  PRODUCTNAME NCHAR(4) NOT NULL 
, PRICE NUMBER(7) NOT NULL 
, MADEDATE DATE 
, COMPANY NCHAR(5) 
, AMOUNT NUMBER(3) NOT NULL 
, CONSTRAINT PRODUCTTBL_PK PRIMARY KEY 
  (
    PRODUCTNAME 
  )
  ENABLE 
);

INSERT INTO MEMBERTBL (MEMBERID, MEMBERNAME, MEMBERADDRESS) VALUES ('KANG', N'강아지', N'서울시 관악구 신림동');
INSERT INTO MEMBERTBL (MEMBERID, MEMBERNAME, MEMBERADDRESS) VALUES ('GOYA', N'고양이', N'경기 성남시 분당구');
INSERT INTO MEMBERTBL (MEMBERID, MEMBERNAME, MEMBERADDRESS) VALUES ('MANG', N'망아지', N'인천 부평시 부평동');
INSERT INTO MEMBERTBL (MEMBERID, MEMBERNAME, MEMBERADDRESS) VALUES ('SONG', N'송아지', N'대전 유성구 도마동');
COMMIT;

INSERT INTO PRODUCTTBL (PRODUCTNAME, PRICE, MADEDATE, COMPANY, AMOUNT) VALUES (N'컴퓨터', '100', TO_DATE('2018-02-14 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'삼성', '19');
INSERT INTO PRODUCTTBL (PRODUCTNAME, PRICE, MADEDATE, COMPANY, AMOUNT) VALUES (N'텔레비젼', '24', TO_DATE('2019-04-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'대우', '20');
INSERT INTO PRODUCTTBL (PRODUCTNAME, PRICE, MADEDATE, COMPANY, AMOUNT) VALUES (N'냉장고', '150', TO_DATE('2017-06-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'LG', '8');
COMMIT;
--MEMBER 이름과 주소 조회 문제
SELECT MEMBERNAME, MEMBERADDRESS FROM MEMBERTBL;
--이름이 고양이인 정보
SELECT * FROM membertbl WHERE membername = '고양이';
--제품이름 가격 남은 수량 조회
SELECT PRODUCTNAME, PRICE, AMOUNT FROM producttbl;
-- 제품 이름 냉장고 정보
SELECT * FROM producttbl WHERE productname = '냉장고';

--CREATE TABLE "my TABLE" (ID NUMBER(3));
--SELECT * FROM "my TABLE";
--DROP TABLE "my TABLE";


