DROP TABLE PRODUCTTBL;
DROP TABLE MEMBERTBL;
DROP SEQUENCE PNO;

--외래키 때문에 PRODUCTTBL부터 DROP 시켜 주어야 됌
CREATE TABLE MEMBERTBL 
(
  MBMERID CHAR(8 BYTE) NOT NULL 
, MEMBERNAME NCHAR(5) NOT NULL 
, MEMBERADDRESS NVARCHAR2(20) 
, CONSTRAINT MEMBERTBL_PK PRIMARY KEY 
  (
    MBMERID 
  )
); 

CREATE TABLE PRODUCTTBL 
(
  PNO NUMBER(5) NOT NULL 
, PRODUCTNAME NCHAR(4) NOT NULL
, MBMERID CHAR(8 BYTE) NOT NULL 
, PRICE NUMBER(7, 0) NOT NULL 
, MADEDATE DATE 
, COMPANY NCHAR(5) 
, AMOUNT NUMBER(3, 0) NOT NULL 
, CONSTRAINT PRODUCTTBL_PK PRIMARY KEY 
  (
    PRODUCTNAME 
  )
);
CREATE SEQUENCE NOSEQ INCREMENT BY 1 START WITH 1;

ALTER TABLE PRODUCTTBL 
DROP CONSTRAINT PRODUCTTBL_PK;

ALTER TABLE PRODUCTTBL
ADD CONSTRAINT PRODUCTTBL_PK PRIMARY KEY 
(
  PNO 
)
USING INDEX 
(
    CREATE UNIQUE INDEX PRODUCTTBL_PK1 ON PRODUCTTBL (PNO ASC) 
)
 ENABLE;
--시퀀스 설정
CREATE TRIGGER PRODUCTTBL_TRG 
BEFORE INSERT ON PRODUCTTBL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PNO IS NULL THEN
      SELECT NOSEQ.NEXTVAL INTO :NEW.PNO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
--/까지 다 가져와야 됌


INSERT INTO MEMBERTBL (MBMERID, MEMBERNAME, MEMBERADDRESS) VALUES ('KANG', N'강아지', N'서울시 관악구 신림동');
INSERT INTO MEMBERTBL (MBMERID, MEMBERNAME, MEMBERADDRESS) VALUES ('MANG', N'망아지', N'인천 부평시 부평동');
INSERT INTO MEMBERTBL (MBMERID, MEMBERNAME, MEMBERADDRESS) VALUES ('GOYA', N'고양이', N'경기 성남시 분당구');
INSERT INTO MEMBERTBL (MBMERID, MEMBERNAME, MEMBERADDRESS) VALUES ('SONG', N'송아지', N'대전 유성구 도마동');
COMMIT;

INSERT INTO PRODUCTTBL (PRODUCTNAME, MBMERID, PRICE, MADEDATE, COMPANY, AMOUNT) VALUES (N'컴퓨터',N'KANG' ,'100', TO_DATE('2018-02-14 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'삼성', '19');
INSERT INTO PRODUCTTBL (PRODUCTNAME, MBMERID, PRICE, MADEDATE, COMPANY, AMOUNT) VALUES (N'텔레비젼',N'SONG' ,'24', TO_DATE('2019-04-27 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'대우', '20');
INSERT INTO PRODUCTTBL (PRODUCTNAME, MBMERID, PRICE, MADEDATE, COMPANY, AMOUNT) VALUES (N'냉장고',N'GOYA' ,'150', TO_DATE('2017-06-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'LG', '8');
COMMIT;

ALTER TABLE PRODUCTTBL
ADD CONSTRAINT PRODUCTTBL_FK1 FOREIGN KEY
(
  MBMERID 
)
REFERENCES MEMBERTBL
(
  MBMERID 
)
ENABLE;

--INSERT INTO PRODUCTTBL (PRODUCTNAME, MBMERID, PRICE, MADEDATE, COMPANY, AMOUNT) VALUES (N'냉장고',N'GOY' ,'150', TO_DATE('2017-06-25 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'LG', '8');
