-- USER SQL
CREATE USER SHOPDEV IDENTIFIED BY 1234
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

-- QUOTAS
ALTER USER SHOPDEV QUOTA 10M ON USERS;

-- ROLES
GRANT CONNECT TO SHOPDEV ;
GRANT RESOURCE TO SHOPDEV ;

-- SYSTEM PRIVILEGES

